# Generated by Django 6.0.1 on 2026-01-21 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(verbose_name="URL")),
                ("code", models.CharField(unique=True, verbose_name="Код URL")),
                (
                    "is_custom",
                    models.BooleanField(verbose_name="Пользовательский ли код"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="urls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владельцы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Короткая ссылка",
                "verbose_name_plural": "Короткие ссылки",
            },
        ),
    ]
