# Generated by Django 6.0.1 on 2026-01-23 21:24

import django.db.models.deletion
import shortener.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(verbose_name="URL")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        error_messages={"unique": "Указанный URL код уже существует."},
                        max_length=50,
                        unique=True,
                        validators=[
                            shortener.validators.code_contains_only_allowed_chars
                        ],
                        verbose_name="URL код",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Короткая ссылка",
                "verbose_name_plural": "Короткие ссылки",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("url", "owner"),
                        name="unique_url_owner",
                        violation_error_message=(
                            "У пользователя уже есть короткий URL для указанного URL."
                        ),
                    )
                ],
            },
        ),
    ]
