# Generated by Django 6.0.1 on 2026-01-23 23:00

import shortener.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                error_messages={"unique": "Указанный URL код уже существует."},
                max_length=50,
                unique=True,
                validators=[shortener.validators.code_contains_only_allowed_chars],
                verbose_name="URL код",
            ),
        ),
    ]
