# Generated by Django 6.0.1 on 2026-02-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0002_alter_shorturl_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
    ]
