# Generated by Django 6.0.1 on 2026-02-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0003_alter_shorturl_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="title",
            field=models.CharField(blank=True, verbose_name="Название"),
        ),
    ]
